name: Ecosystem Greetings Bot

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet Contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Halo! Terima kasih telah menyampaikan masukan di ekosistem resmi M Naufal Amrullah (@mnaufala).'
          pr-message: 'Terima kasih atas kontribusi Anda pada ekosistem M Naufal Amrullah (@mnaufala).'
